In [2]:
import numpy as np
import pandas as pd

In [3]:
ionosphere = pd.read_csv('D:\PIAIC_AIC_Q2_Assignments\Dataset\Ionosphere_DataSet\ionosphere_data.csv')

In [4]:
ionosphere.head(10)

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
5,1,0,0.02337,-0.00592,-0.09924,-0.11949,-0.00763,-0.11824,0.14706,0.06637,...,-0.01535,-0.03240,0.09223,-0.07859,0.00732,0.00000,0.00000,-0.00039,0.12011,b
6,1,0,0.97588,-0.10602,0.94601,-0.20800,0.92806,-0.28350,0.85996,-0.27342,...,-0.81634,0.13659,-0.82510,0.04606,-0.82395,-0.04262,-0.81318,-0.13832,-0.80975,g
7,0,0,0.00000,0.00000,0.00000,0.00000,1.00000,-1.00000,0.00000,0.00000,...,1.00000,1.00000,1.00000,0.00000,0.00000,1.00000,1.00000,0.00000,0.00000,b
8,1,0,0.96355,-0.07198,1.00000,-0.14333,1.00000,-0.21313,1.00000,-0.36174,...,-0.65440,0.57577,-0.69712,0.25435,-0.63919,0.45114,-0.72779,0.38895,-0.73420,g
9,1,0,-0.01864,-0.08459,0.00000,0.00000,0.00000,0.00000,0.11470,-0.26810,...,-0.01326,0.20645,-0.02294,0.00000,0.00000,0.16595,0.24086,-0.08208,0.38065,b

In [5]:
df = pd.DataFrame(ionosphere)

#detecting missing values
df2 = df.isnull()

print(df2)

     feature1  feature2  feature3  feature4  feature5  feature6  feature7  \
0       False     False     False     False     False     False     False
1       False     False     False     False     False     False     False
2       False     False     False     False     False     False     False
3       False     False     False     False     False     False     False
4       False     False     False     False     False     False     False
..        ...       ...       ...       ...       ...       ...       ...
346     False     False     False     False     False     False     False
347     False     False     False     False     False     False     False
348     False     False     False     False     False     False     False
349     False     False     False     False     False     False     False
350     False     False     False     False     False     False     False

     feature8  feature9  feature10  ...  feature26  feature27  feature28  \
0       False     False      False  ...      False      False      False
1       False     False      False  ...      False      False      False
2       False     False      False  ...      False      False      False
3       False     False      False  ...      False      False      False
4       False     False      False  ...      False      False      False
..        ...       ...        ...  ...        ...        ...        ...
346     False     False      False  ...      False      False      False
347     False     False      False  ...      False      False      False
348     False     False      False  ...      False      False      False
349     False     False      False  ...      False      False      False
350     False     False      False  ...      False      False      False

     feature29  feature30  feature31  feature32  feature33  feature34  label
0        False      False      False      False      False      False  False
1        False      False      False      False      False      False  False
2        False      False      False      False      False      False  False
3        False      False      False      False      False      False  False
4        False      False      False      False      False      False  False
..         ...        ...        ...        ...        ...        ...    ...
346      False      False      False      False      False      False  False
347      False      False      False      False      False      False  False
348      False      False      False      False      False      False  False
349      False      False      False      False      False      False  False
350      False      False      False      False      False      False  False

[351 rows x 35 columns]

In [6]:
# shuffle the DataFrame rows
df2 = df2.sample(frac = 1)
  
# print the shuffled DataFrame
print("\nShuffled DataFrame:")
print(df2)

Shuffled DataFrame:
     feature1  feature2  feature3  feature4  feature5  feature6  feature7  \
213     False     False     False     False     False     False     False
315     False     False     False     False     False     False     False
340     False     False     False     False     False     False     False
57      False     False     False     False     False     False     False
327     False     False     False     False     False     False     False
..        ...       ...       ...       ...       ...       ...       ...
8       False     False     False     False     False     False     False
66      False     False     False     False     False     False     False
165     False     False     False     False     False     False     False
231     False     False     False     False     False     False     False
201     False     False     False     False     False     False     False

     feature8  feature9  feature10  ...  feature26  feature27  feature28  \
213     False     False      False  ...      False      False      False
315     False     False      False  ...      False      False      False
340     False     False      False  ...      False      False      False
57      False     False      False  ...      False      False      False
327     False     False      False  ...      False      False      False
..        ...       ...        ...  ...        ...        ...        ...
8       False     False      False  ...      False      False      False
66      False     False      False  ...      False      False      False
165     False     False      False  ...      False      False      False
231     False     False      False  ...      False      False      False
201     False     False      False  ...      False      False      False

     feature29  feature30  feature31  feature32  feature33  feature34  label
213      False      False      False      False      False      False  False
315      False      False      False      False      False      False  False
340      False      False      False      False      False      False  False
57       False      False      False      False      False      False  False
327      False      False      False      False      False      False  False
..         ...        ...        ...        ...        ...        ...    ...
8        False      False      False      False      False      False  False
66       False      False      False      False      False      False  False
165      False      False      False      False      False      False  False
231      False      False      False      False      False      False  False
201      False      False      False      False      False      False  False

[351 rows x 35 columns]